### ISSUE TITLE
Message "Merci d'utiliser les balises de code" absent de la section Web

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCModerationScript#10]
Je n'arrive pas à comprendre pourquoi, mais le message "_Merci d'utiliser les balises de code_" (lignes 82 à 87 du ocreply.json) s'affiche bien dans la section Programmation mais pas dans Site Web.

**Comment by benzouye** [comment]
Version 1.2 correction du bug qui était simplement dû au fait que le tableau des forums utilisé dans le script contenait "Site **w**eb" et non "Site **W**eb" comme c'est le cas sur le site OC ... C'est balot ...
J'en ai profité pour rendre la hauteur du bloc dynamique par rapport au nombre de messages possibles.

**Comment by Lauloque** [comment]
\o/
