### ISSUE TITLE
[Request] Boutons de saut de page

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCModerationScript#12]
Je sais pas pour vous mais moi j'adore les sites où il y a toujours un bouton sous la main pour sauter en haut ou en bas de page.  
Bon, pour le haut, suffit juste d'un lien #. Mais pour le bas...

**Comment by benzouye** [comment]
Je vois l'idée. et c'est assez simple à mettre en oeuvre ...
Tu verrais ces boutons sur toutes les pages, ou seulement sur les sujets, les cours, les forums ?

**Comment by benzouye** [comment]
Version 1.7 dispo avec les deux boutons top/bottom, ils apparaissent selon le positionnement dans la page.
Merci de faire un retour.

**Comment by benzouye** [comment]
J'ai fais des corrections sur l'affichage des boutons (1.7.6) et ils s'affichent sur toutes les pages gérées par le script, à savoir :
openclassrooms.com/forum/*
openclassrooms.com/mp/*
openclassrooms.com/interventions/*
openclassrooms.com/sujets/*

**Comment by Lauloque** [comment]
j'adore ♥
merci \o/
perso je vais plus trop sur le reste du site donc osef. Mais peut-être que d'autres aimeraient avoir ça partout ?

**Comment by benzouye** [comment]
Je clos cette issue, on verra si la demande revient pour le reste du site ;)
