### ISSUE TITLE
[Suggestion] Un système d'infobulles

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCModerationScript#13]
Ça pourrait être bien d'avoir des infobulles pour expliquer les otpions de l'outils ainsi que préciser un modo-message.

**Comment by benzouye** [comment]
I'm on my way ;)

**Comment by benzouye** [comment]
ça va dire quoi "Préciser un modo-message" ? Que le message complet s'affiche dans l'info bulle ? Ou juste le début ?

**Comment by Lauloque** [comment]
je me disais que dans le json on aurait un champ dans les messages pour mettre le contenu de l'infobulle.
Certains messages éxistant dans diverses sections avec des spécificités, ça me semble intéressant d'avoir de quoi écrire ça à la main. Après ça nécessite d'écrire le contenu des infobulles, mais une fois le système établis chacun peut le faire. \o/

**Comment by benzouye** [comment]
Version 1.8.1 disponible. J'ai ajouté un champ "infobulle" dans le JSON dont la valeur est utilisée pour créer le titre des cases à cocher sur la boîte à outils. Affichage via tooltip jQuery.
