### ISSUE TITLE
[Suggestion] Une section "liens utiles"

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCModerationScript#14]
J'ai imaginé qu'on pourrait avoir une petite section "liens utiles", qui s'adapte en fonction de la section où l'on se trouve. Des liens cliquables, avec un p'tit bouton pour les copier directement dans le presse-papier (voire les insérer dans le message à la position actuelle du curseur ?)
Ça nous permettrait d'avoir un accès rapide aux liens des règles générales & de la section où on se trouve, ainsi que les éventuelles FAQ et n'importe quelle ressource que chacun trouverait utile dans sa section.

Un p'tit mockup :

![liens utiles mockup](https://user-images.githubusercontent.com/16049822/38299038-4d606a2c-37f9-11e8-826e-924eec612a49.png)

**Comment by benzouye** [comment]
C'est faisable bien sûr.
J'ai modifié le JSON pour y ajouter cette notion de liens. J'en ai créé deux "standards" pour toutes les sections, je te laisse voir pour ajouter des liens spécifiques.
Par contre je ne vois pas comment gérer cela. Au clic sur le lien il s'ouvrirait dans un nouvel onglet, et au clic sur l'icône il s'insèrerait dans le message ? Sans le mode modération ?
Peux-tu clarifier le fonctionnement que tu vois ?

**Comment by Lauloque** [comment]
j'avais imaginé :
- au clic sur le lien, ça l'ouvre dans un nouvel onglet
- au clic sur l'icone copier, ça copie le lien dans le presse papier
- et si c'est faisable, on ajoute un autre icone (que j'ai pas trouvé) dont le clic provoque l'ajout du lien dans le message là où est le curseur avec mise en forme (j'entend par là `<a href="url">Titre du lien</a>`).

**Comment by benzouye** [comment]
Alors je mets une première version en ligne v1.8.6
Je complèterai rapidement mais déjà si tu as des retours n'hésites pas

**Comment by L0Lock** [comment]
Alors là je n'ai carrément plus de boiteà outils. Juste mes flèches de saut de page.

**Comment by Lauloque** [comment]
J'ai bien des liens cliquables, par contre aucun boutons copier / insérer. C'est normal ?

Petit bug, lorsqu'on clique sur un lien, son infobulle reste affichée :

![gif](https://i.imgur.com/w9z5f7G.gif)

**Comment by benzouye** [comment]
Hélas oui ... c'est un bug jQuery connu ... mais non corrigé ... cela est dû au changement de contexte à l'ouverture d'un nouvel onglet ... Une (piètre) solution c'est de faire "Ctrl+Clic" pour ne pas accéder directement au nouvel onglet ouvert mais rester sur l'onglet courant.

Soit on modifie le fonctionnement en retirant la possibilité d'ouvrir dans un nouvel onglet, soit en fork jQuery pour corriger le bug (mouhahaha), soit ... soit je sais pas ...

T'en penses quoi ?

**Comment by benzouye** [comment]
PS : un clic droit sur l'info bulle résistante la fait disparaître ;)

**Comment by benzouye** [comment]
Version 1.8.6 en ligne, j'ai juste rajouté l'icône pour ajouter les liens dans le message.
Je galère un peu sur le "copie presse papier"  ...

**Comment by Lauloque** [comment]
C'est déjà un gros avancement \o/

**Comment by benzouye** [comment]
v1.9.2 : Presse papier opérationnel.
J'ai par contre ajouté une bibliothèque ClipBoardJS pour me simplifier la vie ...

**Comment by Lauloque** [comment]
Pas de soucis. Il y a moyen d'insérer le lien là ou est le curseur dans l'éditeur ? Pour l'instant ça ajoute à la fin du message dans un nouveau `<p>`.

**Comment by benzouye** [comment]
C'est good v1.9.4

**Comment by benzouye** [comment]
v1.9.5 correction de bug sur l'insertion du lien en place du curseur
