### ISSUE TITLE
[Bug] Certains messages inaccessibles

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCModerationScript#16]
Les messages 22 et 24, respectivement "Recrutement progrssionnels" et "Accepter la critique" ont été ajoutés il y a quelques jours maintenant, mais sont toujours invisibles chez moi malgré les multiples refresh de réponses.
Pourtant la réponse 23 "Sujet résolu" a bien été ajoutée à mon panneau.
RIP mes modos messages :(

**Comment by benzouye** [comment]
Erreur trouvée ... Dans le traitement des messages j'avais mis un _break_ au lieu d'un _continue_ ...
V1.8.5 release !
