### ISSUE TITLE
[BUG] Ça veut plus s'ouvrir :'(

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCModerationScript#17]
![gif](https://i.imgur.com/ooAmuXS.gif)

Ben ça veut plus s'ouvrir :'(

**Comment by benzouye** [comment]
WOW ! Alors j'ai publié la v1.8.5 entre temps, et je ne reproduit pas ...
Peux-tu confirmer le bug, et si oui, y a-t-il des erreurs dans la console JS ?

**Comment by Lauloque** [comment]
j'avais fait la mise à jour depuis, toujours pareil, rien dans la console.
J'ai réinstallé tampermonkey et le script, et ça fonctionne maintenant. On va dire que c'est la faute à tampermonkey du coup ?

**Comment by benzouye** [comment]
Mystère ...
