### ISSUE TITLE
Classer les réponses

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCModerationScript#18]
On commence à avoir beaucoup de réponses maintenant, et ça devient peu à peu le bazar dans la boîte à outils.
Est-ce qu'il y aurait moyen de trier les messages ?

Par exemple regrouper les messages communs à toutes les sections en haut (il me semble que ceux-là sont tous tagués via "all") et laisser les messages spécifiques en dessous. Ça serait déjà pas mal, ça évitera d'aller chercher des messages partout dans la liste.

Et ensuite, peut-être encore trier les messages selon leur similarité ou leur fréquence d'utilisation ? Ce dernier point demandera un peu de réflexion et des retours des autres.

Si je dis pas de bêtises pour l'instant le tri se fait en fonction de l'ID. Peut-être que la solution simple à court terme serait de se décider des intervalles d'ID qui correspondent à un tri. Par exemple tous les messages commun ont un ID 1xx, les messages code 2xx, etc...

**Comment by benzouye** [comment]
Je suis d'accord avec toi.

Aucun tri n'est fait en fait ... Les messages apparaissent dans l'ordre du JSON. Si tu mettais l'id 30 au début, il sortirait en premier dans la boîte à outil ...

J'avais déjà pensé à regrouper les messages en fonction des sections, au moins "all" en premier et le reste après. Cela peut s'envisager assez facilement ... Je vais travailler sur ce point, pour regrouper les messager par section.

Par ailleurs, on peut aussi se poser la question de la pertinence des messages, sont-ils tous utiles ?
Mais nous n'avons aucun moyen de connaître le nombre d'utilisations par message ... Il faudrait presque développer une base de données avec des logs "qui a posté quoi" ...  Ce serait überklass !

**Comment by Lauloque** [comment]
moi je crois me servir de tous pour l'instant.
En fait ça sert à quoi l'ID du json ?

**Comment by benzouye** [comment]
> En fait ça sert à quoi l'ID du json ?

Comme tout identifiant, il sert à identifier chaque message de façon unique et à le retrouver dans la liste (tableau) quand on en a besoin. C'est plus facile de recherche "9" que de rechercher "Manque de recherche" ... il est préférable de travailler avec des entiers plutôt que des chaînes de caractères ...

Bon je vais me pencher sur ce sujet, mais cela risque d'agrandir encore la taille de la boîte à outils !

**Comment by benzouye** [comment]
Version 1.9.0 en ligne
Comme évoqué juste avant, la taille de la boîte devient limite en mode vertical (celui que j'utilise le plus).
Merci pour tes retours

**Comment by Lauloque** [comment]
C'est ce que j'utilise aussi ^^
Je pense pas qu'il est nécessaire e physiquement séparer les messages avec un titre, les classer suffit amha. Ou alors une séparation qui prend peu de place, genre un `<hr>`

**Comment by benzouye** [comment]
v1.9.1, j'ai remplacé les titres par un hr, c'est plus léger j'aime bien. Les messages sont également triés par ordre alphabétique de titre ...

**Comment by Lauloque** [comment]
C bô ! ♥
Peut-être qu'au bout d'un moment ça sera également nécessaire pour les liens.

**Comment by benzouye** [comment]
C'est fait aussi pour les liens v1.9.4

**Comment by Lauloque** [comment]
\o/
