### ISSUE TITLE
Bug - le bouton supprimer + mp ne supprime pas

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCModerationScript#20]
Ça doit faire la deuxième fois au moins que j'utilise le bouton sensé supprimer un message et envoyer un mp, que j'envoie le dit mp, et que le message n'est pas supprimé apès tout ça.

RIP :'(

**Comment by benzouye** [comment]
Oula ! ça va être dur de comprendre le pourquoi du comment ...
Personnellement je n'ai pas encore rencontré ce bug ...
v1.9.13 : J'ai rajouté une trace dans le code JS qui devrait afficher des messages dans la console en arrivant sur la fenêtre MP. Tiens moi au courant.

**Comment by benzouye** [comment]
v1.9.14 ... faute de frappe ...

**Comment by benzouye** [comment]
Des nouvelles L0Lock ? Ou je ferme ?

**Comment by Lauloque** [comment]
Il me semble que oui. Au pire des cas je ré-ouvrirais.
