### ISSUE TITLE
Ajouter le titre originel pour référence quand on ajoute le message auto "Mauvais titre"

### ISSUE THREAD

**Issue by Lamecarlate** [L0Lock/OCModerationScript#21]
Ça serait cool d'afficher quelque part dans le message auto le titre originel quand on demande à le modifier - je me souviens rarement de ce titre, et quelque fois on ne peut pas savoir ce qui a été effectivement fait.

AbcAbc6 a une tactique : il écrit en tout piti le titre originel, à la main. Je fais de même, et c'est bien pratique.

Ça le serait encore plus si c'était automatique :sparkles: 

(problème éventuel : ça implique un cas particulier, une action particulière pour un message spécifique)

**Comment by Lauloque** [comment]
J'approuve.  
Parcontre j'ai pas compris de quel problème tu parle.

**Comment by benzouye** [comment]
@L0Lock : Tous les messages sont traités de la même manière par le script, donc vouloir un comportement différent pour un message complique un peu le schmilblick ...
Mais je vais y réfléchir (avec une balise par exemple) ...

**Comment by benzouye** [comment]
Et bim ;)

**Comment by Lauloque** [comment]
marche pô
![](https://i.imgur.com/SX12wk2.png)

**Comment by benzouye** [comment]
Il faut "mettre à jour les réponses" pour avoir la liste des messages qui utilisent cette option ;)
v1.0.5
![image](https://user-images.githubusercontent.com/4947952/41546142-278bc77e-731d-11e8-8df0-2648f97c7880.png)

**Comment by Lamecarlate** [comment]
Alors moi j'aurais pas mis ça si visible, et surtout je n'y aurais pas inclus le sous-titre.

Ça vous va si je fais une modif ? Titre uniquement, à la fin du message, et en taille "8pt" ? (l'idée c'est d'être une référence pour nous, pas pour les autres membres)

**Comment by benzouye** [comment]
Pas de souci, juste retoucher les lignes 351 à 355. J'utiliserai plutôt du "em"/"rem" que du "pt" ...

**Comment by Lauloque** [comment]
Ça ne fonctionne toujours pas chez moi :'(

Script v2.1.0 réponses v1.0.6

**Comment by Lamecarlate** [comment]
>  J'utiliserai plutôt du "em"/"rem" que du "pt" ...

Oui oui bien sûr, j'ai dit de mémoire parce que je crois que c'est la taille donnée dans le wysiwyg (j'utilise la taille "1 (8pt)").

(et c'est fait)

**Comment by benzouye** [comment]
Moi la modif me va bien ainsi (titre en petit en bas du message), et pour @L0Lock , ça fonctionne nickel chez moi ... tu peux vérifier de nouveau v2.1.2 (script) et v1.0.6 (réponses).

**Comment by Lauloque** [comment]
Ça y est ! Ça marche ! \o/

**Comment by Lauloque** [comment]
Est-ce que c'est possible de mettre le titre en italique ? Histoire qu'il se démarque de la mention:

(Titre original : *Mon super titre qu'il est explicite et pas en fullcapses*)

**Comment by Lamecarlate** [comment]
@L0Lock Your wish is my command*

(dans le cadre du script et dans les limites légales bien entendu)

**Comment by Lauloque** [comment]
punaise tu m'as fait fantasmer pendant dix secondes 😊 
Puis j'ai lu la parenthèse....

![](https://i.imgur.com/fDtGpSY.gif)
