### ISSUE TITLE
[Bug] suivi automatique des topics visités

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCModerationScript#22]
Ça fait plusieurs fois que je me retrouve notifié des messages de topics où je n'ai rien fait et ne me usis pas inscrit. Je crois avoir une piste de pourquoi:

J'ai visité [ce topic](https://openclassrooms.com/forum/sujet/choix-hebergement-agence) tout à l'heure, je n'ai rien fait à part lire et fermer. Et maintenant je me retrouve notifié des nouvelles réponses.

J'en déduis donc la possibilité que la simple visite d'un topic m'y inscrit 🤔

**Comment by Lamecarlate** [comment]
Tiens, c'est bizarre. Je me suis déjà retrouvée notifiée de topics où j'avais posté puis supprimé mon message, mais ce que tu décris, jamais.

**Comment by benzouye** [comment]
> Tiens, c'est bizarre. Je me suis déjà retrouvée notifiée de topics où j'avais posté puis supprimé mon message, mais ce que tu décris, jamais.

Ce comportement est normal, lorsque tu postes tu t'inscris aux notifications, mais lorsque tu supprimes, cela ne retire pas l'inscription. Par ailleurs ce n'est pas induis par le script mais c'est une fonctionnalité "native" du forum.

> J'ai visité ce topic tout à l'heure, je n'ai rien fait à part lire et fermer. Et maintenant je me retrouve notifié des nouvelles réponses.

Là c'est bizarre ... Même réponse par contre, ce n'est pas induis par le script, car il n'agit pas sur les notifications ... Donc pour moi c'est un bug "natif" du forum ...
Personnellement je n'ai jamais eu le cas.

**Comment by Lamecarlate** [comment]
Ah oui, pour moi c'était natif, et je pensais que @L0Lock postait pour en parler et non pour demander une réparation ^^

> Ce comportement est normal, lorsque tu postes tu t'inscris aux notifications, mais lorsque tu supprimes, cela ne retire pas l'inscription.

Pour moi c'est pas normal, non. Et c'est un bug du forum. Maiiis bon c'est rare et limité à l'équipe de modération donc ça ne sera pas réparé, on le sait.
