### ISSUE TITLE
Ajouter des labels pour les inputs

### ISSUE THREAD

**Issue by Lamecarlate** [L0Lock/OCModerationScript#23]
Actuellement il faut cliquer sur l'input lui-même pour sélectionner un message à ajouter. C'est tout pitit, c'est relou, c'est peu accessible : il faut agrandir la zone d'action. 

Je propose donc (et je le ferai d'ici quelques jours, laissez-moi assignée à l'issue) de mettre des labels associés aux inputs, englobant le texte, permettant de cliquer sur ledit texte à chaque fois.

**Comment by benzouye** [comment]
C'est bon c'est réglé ;)

**Comment by Lamecarlate** [comment]
… euh, je me suis assigné le ticket, j'ai marqué explicitement que je voulais le garder. J'avais envie de le faire, ce truc. J'aurais aimé qu'on respecte ça.

**Comment by benzouye** [comment]
Désolé... tu veux que je fasse un rollback pour faire la modif à ta façon?

**Comment by Lamecarlate** [comment]
Nope, c'est plus ou moins ce que j'aurais fait (l'autre manière possible c'est de mettre des id sur les inputs pour le "for" des labels). Pas grave. 

(par contre, faut vraiment qu'on trouve comment charger un petit css à côté, parce que les styles inline c'est un peu lourd)

**Comment by benzouye** [comment]
> par contre, faut vraiment qu'on trouve comment charger un petit css à côté, parce que les styles inline c'est un peu lourd

J'ai testé avec un CSS à part, mais c'est très long à charger et donne un "à coup" à l'affichage ... pas glop !
Du coup j'ai regroupé tout le code CSS géré avec jQuery.css en un seul endroit en fin de code. C'est un peu plus propre ;)
