### ISSUE TITLE
MAJ des messages inbox

### ISSUE THREAD

**Issue by benzouye** [L0Lock/OCModerationScript#24]
Suite à proposition je crée cette issue pour vous proposer de mettre le bouton de MAJ des messages directement dans la boîte à outils.
![refresh](https://user-images.githubusercontent.com/4947952/42333056-f6bde9dc-8079-11e8-9ea1-4cf513094b77.png)
Merce de me donner votre avis ;)

**Comment by Lauloque** [comment]
Génial ! 😄
