### ISSUE TITLE
Adapter selon le forum le texte "class="brush: c;"

### ISSUE THREAD

**Issue by albertaljeanpierre** [L0Lock/OCModerationScript#25]
Bonjour, concernant le modo message "mise en forme du code" serait il possible de varier le message selon le forum ou le message est poster. class="brush: c;" si le message est poster dans le forum c et class="brush: python;" si le message est poster dans le forum python. Merci https://openclassrooms.com/forum/sujet/opencv-stereovision-anarchique?page=1#message-92520040

**Comment by benzouye** [comment]
Je rajoute un élément "code" dans le tableau des sections, et je mets un test dans la génération du message pour remplacer par le nom du code dans le message "mise en forme du code"
V2.7.0 dispo + mise à jour des réponses nécessaire ;)
