### ISSUE TITLE
Modo-message mauvais titre : l'ancien titre n'est pas renseigné

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCModerationScript#26]
Dans le modo-message "mauvais titre", le titre original du sujet n'est plus renseigné:

![](https://i.imgur.com/aD5EFda.png)

OCM 2.8.0
Réponses 1.2.2
Opera - W10 pro
Pain au chocolat

Ce qui se passe dans la console :
```
non-human click detected, skipping
userscript.html?id=598bba5b-2a0a-4237-a664-9cca4ba76243:389 Stop suivi https://openclassrooms.com/fr/sujets/suivis/supprimer/google-sheets-duplication/JPjqVwLfsW-xwt8nQ5ggxlBJwDJl20ATLAoFcC6PZaw
```

**Comment by benzouye** [comment]
Je suppose fortement que OC est en train de faire des modifications dans la structure HTML du forum.
Du coup il n'est pas impossible que nous rencontrions des problèmes de ce genre ailleurs dans le script ...
Je corrige celui-ci déjà :P
