### ISSUE TITLE
[Suggestion] Nettoyer les signalements d'un sujet

### ISSUE THREAD

**Issue by Lauloque** [L0Lock/OCModerationScript#27]
Ça serait pratique si on avait un bouton pour nettoyer toutes les alertes d'un sujet. Ou au moins, toutes les alertes de la page.

Typiquement, les sujets où passent des utilisateurs de ce type :
![image](https://user-images.githubusercontent.com/16049822/53003919-558eb080-3430-11e9-8479-fc4ed2c3271a.png)

On serait content de pouvoir nettoyer d'un clic...

Pour ce qui est du côté visuel, la boite à outils est déjà bien remplie, et je pense que ça sera pas très pratique d'avoir un bouton fixé à la page. Peut-être qu'un bouton flottant, à côté des boutons de navigation qu'on a déjà à droite, pourrait être bien (pas trop collé non plus, qu'on ne clique pas dessus par erreur, ou alors qu'il y ait un message de confirmation d'abord (peut-être qu'il en faudrait un de toutes façons ?))

On pourrait utiliser l'unicode "wastebasket" pour l'icône : 🗑

**Comment by benzouye** [comment]
Dans les options actuelles il existe la possibilité de faire cela, en cochant la case :
![image](https://user-images.githubusercontent.com/4947952/53338401-db649d00-3903-11e9-8980-650df142fefd.png)
Cela oblige à poster un message par contre ...
Je regarde quand même pour faire un bouton flottant ?

**Comment by Lauloque** [comment]
Qui ne nécessite pas de poster oui.

Aussi, est-ce que l'option "retirer les alertes" fonctionne sur toutes les alertes du sujet ? C'est pas limité à la page actuelle ?

**Comment by benzouye** [comment]
Alors en effet, la case à cocher actuelle ne traite que la page courante ... mais je ne saurais pas comment faire pour traiter tout le sujet (toutes ses pages) en une seule fois ...
Donc OK pour mettre un bouton flottant mais qui ne traitera toujours que la page courante ... je le mets où du coup ? A gauche des messages, flottant comme les top et bottom de droite ?

**Comment by Lauloque** [comment]
AMHA c'est le mieux comme affichage oui

**Comment by benzouye** [comment]
J'ai fait un commit https://github.com/L0Lock/OCModerationScript/commit/ad7142eb6aad239ee7417b9be54eb399cdc249de
Il faudra tester, car là, pas d'alertes en cours ...

**Comment by benzouye** [comment]
Contrôlé à l'instant, ça marche !
